---
- name: Playbook to Deploy Nginx on Webserve Servers And Start The Service
  hosts: Webservers:appservers:dbservers
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
- name: Perform Apt Update
  shell: apt update

- name: Install Nginx
  shell: apt install -y nginx 

- name: Start Nginx Service
  shell: Service Nginx start 

- name: Delete Existing File
  shell: rm -rf /tmp/passwd 
  
- name: Copyfile
  copy:
    src: /etc/passwd
    dest: /tmp/passwd   

- name: Read File
  shell: cat /tmp/passwd