---
- name: Install Nginx on Ubuntu
  hosts: all
  become: true
  
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable Nginx
      systemd:
        name: nginx
        enabled: yes
        state: started
